' SAP GUI Scripting Auto-generated by SAP Close-Up Automation Tool
' -----------------------------------------------------------------------
' This script is intended to be run on a Windows machine with SAP GUI installed.
' It automates SAP interactions for the close-up process.
' -----------------------------------------------------------------------

' Error handling
On Error Resume Next
Dim errScript
Set errScript = CreateObject("Scripting.Dictionary")

' Initialize SAP connection
Function ConnectToSAP()
    Dim SapGuiAuto, Application, Connection, Session
    
    ' Get SAP GUI Scripting object
    Set SapGuiAuto = GetObject("SAPGUI")
    Set Application = SapGuiAuto.GetScriptingEngine
    
    ' Check if SAP GUI is running
    If IsObject(Application) Then
        ' Use existing connection if available
        If Application.Connections.Count > 0 Then
            Set Connection = Application.Connections(0)
            Set Session = Connection.Children(0)
            ConnectToSAP = True
            Set GetSapSession = Session
        Else
            MsgBox "No active SAP connections found. Please log in to SAP first.", 16, "Error"
            ConnectToSAP = False
        End If
    Else
        MsgBox "SAP GUI Automation is not available. Please make sure SAP GUI is running and scripting is enabled.", 16, "Error"
        ConnectToSAP = False
    End If
End Function

' Get SAP session
Function GetSapSession()
    Dim SapGuiAuto, Application, Connection
    
    ' Get SAP GUI Scripting object
    Set SapGuiAuto = GetObject("SAPGUI")
    Set Application = SapGuiAuto.GetScriptingEngine
    
    ' Use existing connection
    Set Connection = Application.Connections(0)
    Set GetSapSession = Connection.Children(0)
End Function

' Check if error occurred
Function CheckError()
    If Err.Number <> 0 Then
        errScript.Add Err.Number, Err.Description
        CheckError = False
    Else
        CheckError = True
    End If
    Err.Clear
End Function

' Display errors if any
Sub ShowErrors()
    If errScript.Count > 0 Then
        Dim errorMsg
        errorMsg = "The following errors occurred:" & vbCrLf
        
        For Each errNum In errScript.Keys
            errorMsg = errorMsg & "Error " & errNum & ": " & errScript(errNum) & vbCrLf
        Next
        
        MsgBox errorMsg, 16, "Script Errors"
    End If
End Sub

' Service Order Number
Dim ServiceOrderNumber
ServiceOrderNumber = "5019579117"


' Main script execution
If ConnectToSAP() Then
    Dim Session
    Set Session = GetSapSession()
    
    ' Navigate to ZIWBN transaction
    Session.StartTransaction "ZIWBN"
    CheckError()
    
    ' Enter service order number and execute
    Session.FindById("wnd[0]/usr/ctxtSO_AUFNR-LOW").Text = ServiceOrderNumber
    Session.FindById("wnd[0]/usr/ctxtSO_AUFNR-LOW").CaretPosition = 12
    Session.FindById("wnd[0]/tbar[1]/btn[8]").Press ' Execute
    CheckError()
    
    ' Make sure we have results
    If Session.FindById("wnd[0]/usr/cntlCUSTOM/shellcont/shell/shellcont/shell").RowCount > 0 Then
        ' Select the first row
        Session.FindById("wnd[0]/usr/cntlCUSTOM/shellcont/shell/shellcont/shell").SelectedRows = "0"
        Session.FindById("wnd[0]/usr/cntlCUSTOM/shellcont/shell/shellcont/shell").DoubleClickCurrentCell
        CheckError()
        
        MsgBox "ZIWBN opened successfully for order " & ServiceOrderNumber, 64, "Success"
    Else
        MsgBox "No data found for order " & ServiceOrderNumber & " in ZIWBN", 16, "Error"
    End If
End If

ShowErrors()
